"""Glue between the 11-axis Sobol design and the Pulse Physiology Engine.

Responsibilities, kept in one file:

1. :func:`design_row_to_scenario_params` — pure mapping from a Sobol row to a
   Pulse scenario parameter dict (environment file, duration, FiO₂ tag).
2. :func:`render_pulse_script` — string-templated Python script that runs
   inside the ``pulse-ds:4.3.1`` container.
3. :func:`extract_pulse_outputs` — pure pandas; extracts ``cerebral_o2_min``
   (proxied by ``min(OxygenSaturation)``) from the engine's CSV output.
4. :func:`make_pulse_row_fn` — composes the above plus a Docker invocation
   into the per-row callable consumed by :class:`PulseRunner`.

**Orthogonal-oracle scope (locked by deep_dive_1 §2)**: Pulse models the
hypoxia physiology that CGEM lacks (altitude, FiO₂, SaO₂ trajectories);
CGEM models the +Gz hydrostatic / consciousness dynamics that Pulse cannot
represent. PulseRunner therefore consumes only ``fio2_inspired`` and
``sao2_baseline`` from the Sobol row plus a baseline pilot state; the Gz /
strain / tilt / anthropometry axes are out of scope for this oracle.

**v1 mapping caveat**: FiO₂ is mapped to one of three pre-built Pulse
environment files by threshold rather than driving the ambient O₂ gas
fraction directly. Phase 4.8 refinement is to set the gas fraction via
``SEChangeEnvironmentalConditions`` so the surface is continuous rather
than tier-quantized.
"""
from __future__ import annotations

import os
import subprocess
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from pulse_research.api.runners import RowFn, RowOutput

PULSE_IMAGE_ENV_VAR = "PULSE_DOCKER_IMAGE"
PULSE_WORK_DIR_ENV_VAR = "PULSE_WORK_DIR"
DEFAULT_PULSE_IMAGE = "pulse-ds:4.3.1"
DEFAULT_DURATION_S = 60.0
DEFAULT_PATIENT_STATE = "./states/StandardMale@0s.json"

# FiO₂ -> Pulse environment file (locked thresholds; see plan §"Axis mapping")
_ENV_STANDARD = "./environments/Standard.json"
_ENV_HYPO_3000 = "./environments/Hypobaric3000m.json"
_ENV_HYPO_4000 = "./environments/Hypobaric4000m.json"


def design_row_to_scenario_params(
    row: np.ndarray,
    *,
    duration_s: float = DEFAULT_DURATION_S,
) -> dict[str, Any]:
    """Map an 11-axis Sobol row to a Pulse scenario parameter dict.

    Returns keys: ``fio2_inspired``, ``sao2_baseline``, ``environment_file``,
    ``patient_state_file``, ``duration_s``.
    """
    if row.ndim != 1 or row.shape[0] != 11:
        raise ValueError(f"row must be shape (11,); got {row.shape}")

    fio2 = float(row[9])
    sao2 = float(row[10])

    if fio2 >= 0.20:
        env_file = _ENV_STANDARD
    elif fio2 >= 0.16:
        env_file = _ENV_HYPO_3000
    else:
        env_file = _ENV_HYPO_4000

    return {
        "fio2_inspired": fio2,
        "sao2_baseline": sao2,
        "environment_file": env_file,
        "patient_state_file": DEFAULT_PATIENT_STATE,
        "duration_s": float(duration_s),
    }


_SCRIPT_TEMPLATE = '''"""Pulse altitude-hypoxia scenario (auto-generated by pulse_glue.render_pulse_script).

Parameters:
  fio2_inspired   = {fio2_inspired}
  sao2_baseline   = {sao2_baseline}
  environment     = {environment_file}
  patient_state   = {patient_state_file}
  duration_s      = {duration_s}
"""
import sys
sys.path[0:0] = ["/pulse/python", "/pulse/bin"]

from pulse.engine.PulseEngine import PulseEngine
from pulse.cdm.engine import SEDataRequest, SEDataRequestManager
from pulse.cdm.scalars import FrequencyUnit, PressureUnit
from pulse.cdm.environment_actions import SEChangeEnvironmentalConditions

drm = SEDataRequestManager([
    SEDataRequest.create_physiology_request("HeartRate", unit=FrequencyUnit.Per_min),
    SEDataRequest.create_physiology_request("OxygenSaturation"),
    SEDataRequest.create_physiology_request(
        "ArterialBloodOxygenPartialPressure", unit=PressureUnit.mmHg
    ),
    SEDataRequest.create_physiology_request("RespirationRate", unit=FrequencyUnit.Per_min),
])
drm.set_results_filename("./test_results/scenario.csv")

pulse = PulseEngine()
pulse.set_log_filename("./test_results/pulse.log")
pulse.log_to_console(False)
if not pulse.serialize_from_file("{patient_state_file}", drm):
    raise RuntimeError("Pulse Engine failed to load state: {patient_state_file}")

action = SEChangeEnvironmentalConditions()
action.set_environmental_conditions_file("{environment_file}")
pulse.process_action(action)

pulse.advance_time_s({duration_s})
pulse.clear()
'''


def render_pulse_script(params: dict[str, Any]) -> str:
    """Render the per-row Pulse Python script as a string."""
    return _SCRIPT_TEMPLATE.format(**params)


def extract_pulse_outputs(df: pd.DataFrame) -> dict[str, float | None]:
    """Pure: derive scalar outputs from a Pulse CSV DataFrame.

    Pulse names columns descriptively (e.g. ``OxygenSaturation``,
    ``ArterialBloodOxygenPartialPressure(mmHg)``). We look up by substring
    match so unit-suffix variation does not break the parse.
    """
    spo2_col = next((c for c in df.columns if "OxygenSaturation" in c), None)
    cerebral_o2_min: float | None = None
    if spo2_col is not None and not df[spo2_col].dropna().empty:
        cerebral_o2_min = float(df[spo2_col].min())
    return {
        "cerebral_o2_min": cerebral_o2_min,
        "time_to_gloc_s": None,  # Pulse does not model G-LOC events
    }


def _default_work_dir_factory() -> Path:
    return Path(tempfile.mkdtemp(prefix="pulse_row_"))


def _build_docker_cmd(
    *,
    image: str,
    work_dir: Path,
    results_dir: Path,
    script_name: str,
) -> list[str]:
    return [
        "docker",
        "run",
        "--rm",
        "-w",
        "/pulse/bin",
        "-e",
        "PYTHONPATH=/pulse/python:/pulse/bin",
        "-v",
        f"{results_dir}:/pulse/bin/test_results",
        "-v",
        f"{work_dir}:/work",
        image,
        "python3",
        f"/work/{script_name}",
    ]


def make_pulse_row_fn(
    *,
    image: str | None = None,
    work_dir_factory: Callable[[], Path] | None = None,
    subprocess_runner: Callable[..., Any] | None = None,
    timeout_s: float = 180.0,
    duration_s: float = DEFAULT_DURATION_S,
) -> RowFn:
    """Build the per-row callable bound to the ``pulse-ds:4.3.1`` Docker image.

    Parameters
    ----------
    image:
        Docker image name; defaults to the ``PULSE_DOCKER_IMAGE`` env var or
        ``"pulse-ds:4.3.1"``.
    work_dir_factory:
        Returns a fresh ``Path`` per row. Default creates a tempdir.
    subprocess_runner:
        Injectable for tests. Signature compatible with :func:`subprocess.run`;
        must raise on non-zero exit (i.e., ``check=True`` semantics).
    timeout_s:
        Docker run timeout in seconds.
    duration_s:
        Pulse simulation duration in seconds (advanced past the env-change
        action).
    """
    resolved_image = image or os.environ.get(PULSE_IMAGE_ENV_VAR, DEFAULT_PULSE_IMAGE)
    factory = work_dir_factory or _default_work_dir_factory
    runner = subprocess_runner or subprocess.run

    def _row_fn(row: np.ndarray) -> RowOutput:
        try:
            params = design_row_to_scenario_params(row, duration_s=duration_s)
            work_dir = factory()
            results_dir = work_dir / "results"
            results_dir.mkdir(parents=True, exist_ok=True)
            script_name = "scenario.py"
            (work_dir / script_name).write_text(render_pulse_script(params))

            cmd = _build_docker_cmd(
                image=resolved_image,
                work_dir=work_dir,
                results_dir=results_dir,
                script_name=script_name,
            )
            runner(cmd, check=True, timeout=timeout_s, capture_output=True)

            csv_path = results_dir / "scenario.csv"
            df = pd.read_csv(csv_path)
            outputs = extract_pulse_outputs(df)
        except Exception as e:
            return RowOutput(time_to_gloc_s=None, cerebral_o2_min=None, error=str(e))

        return RowOutput(
            time_to_gloc_s=outputs["time_to_gloc_s"],
            cerebral_o2_min=outputs["cerebral_o2_min"],
        )

    return _row_fn
